storage_uri: 'storage'

tasks:
  - name: 'twitter'
    command: 'node'
    path: 'collector/twitter.js'
  - name: 'normalize'
    command: 'python'
    path: 'tasks/normalize.py'
  - name: 'sentiment'
    command: 'python'
    path: 'tasks/sentiment.py'

processors:
  - name: 'tweets'
    id_prop: 'id'
    collector_tasks:
      twitter: tweet
    sync_tasks:
      normalize: normalized_text
    async_tasks:
      sentiment: sentiment
  - name: 'users'
    id_prop: 'id'
    collector_tasks:
      twitter: user
    sync_tasks: {}
    async_tasks: {}