storage_uri: 'storage'

tasks:
  # Collector
  - name: 'twitter'
    command: 'node'
    path: 'collector/twitter.js'

  # Text Analyzing
  - name: 'spacy.stopwords'
    command: 'python'
    path: 'tasks/spacy_tasks/normalize.py'
  - name: 'spacy.tree'
    command: 'python'
    path: 'tasks/spacy_tasks/tree.py'

  # Sentiment Task
  - name: 'google.sentiment'
    command: 'node'
    path: 'tasks/google/sentiment.js'

processors:
  - name: 'tweets'
    id_prop: 'id'
    collector_tasks:
      twitter: tweet
    sync_tasks:
      normalized_text: spacy.stopwords
    async_tasks:
      trees: spacy.tree
      sentiment: google.sentiment
  - name: 'users'
    id_prop: 'id'
    collector_tasks:
      twitter: user
    sync_tasks: {}
    async_tasks: {}