storage_uri: 'storage'

tasks:
  # Collector
  - name: 'twitter'
    command: 'node'
    path: 'collector/twitter.js'

  # Text Analyzing
  - name: 'stopwords'
    command: 'python'
    path: 'tasks/spacy_tasks/normalize.py'
  - name: 'tree'
    command: 'python'
    path: 'tasks/spacy_tasks/tree.py'

  # Sentiment Task
  - name: 'sentiment'
    command: 'node'
    path: 'tasks/google/sentiment.js'

processors:
  - name: 'tweets'
    id_prop: 'id'
    collector_tasks:
      twitter: tweet
    sync_tasks:
      stopwords: normalizedText
    async_tasks:
      tree: syntaticTree
      sentiment: sentiment
  - name: 'users'
    id_prop: 'id'
    collector_tasks:
      twitter: user
    sync_tasks: {}
    async_tasks: {}