version: '3'
services:
  collector:
    build: ./collector
    env_file: ./prod.env
    ports:
      - 8080:8080
  specialist_app:
    build: ./specialist-app
    env_file: ./prod.env
    links:
      - specialist_api
    ports:
      - 3000:3000
  tasks:
    image: dumont_tasks
    command: python update_data.py tweets --times 1
    env_file: ./prod.env
  specialist_api:
    build: ./specialist-api
    env_file: ./prod.env
    ports:
      - 8081:8081