version: '3'
services:
  collector:
    build: ./collector
    env_file: ./prod.env
    ports:
      - 8080:8080
  specialist_app:
    build: ./specialist-app
    env_file: ./prod.env
    links:
      - specialist_api
    ports:
      - 3000:3000
  tasks:
    build: ./tasks
    command: python update_data.py tweets --level 0 --skiplvl 1 --times 2
    env_file: ./prod.env
    volumes:
      - ./tasks:/tasks
  specialist_api:
    build: ./specialist-api
    env_file: ./prod.env
    ports:
      - 8081:8081