export const ANALYZE_SAVE_FETCH = 'ANALYZE_SAVE_FETCH';

export const TWEET_ON_LIST_STAGES = [
    'TWEET_ON_LIST_FETCHING',
    'TWEET_ON_LIST_FETCH',
    'TWEET_ON_LIST_FAIL_FETCH'
];

export const ANALYZE_SAVE_STAGES = [
    'ANALYZE_SAVE_FETCHING',
    ANALYZE_SAVE_FETCH,
    'ANALYZE_SAVE_FAIL_FETCH',
]