export const UPDATE_SESSION_FORM = 'UPDATE_SESSION_FORM';
export const SPECIALIST_LOGIN = 'SPECIALIST_LOGIN';
export const SPECIALIST_LOGOUT = 'SPECIALIST_LOGOUT';
export const CREATE_SESSION_FETCH = 'CREATE_SESSION_FETCH';
export const DESTROY_SESSION_FETCH = 'DESTROY_SESSION_FETCH';

export const CREATE_SESSION_STAGES = [
    'CREATE_SESSION_FETCHING',
    CREATE_SESSION_FETCH,
    'CREATE_SESSION_FAIL_FETCH'
];

export const DESTROY_SESSION_STAGES = [
    'DESTROY_SESSION_FETCHING',
    DESTROY_SESSION_FETCH,
    'DESTROY_SESSION_FAIL_FETCH'
];
