export const ADD_ANSWER = 'ADD_ANSWER';
export const UPDATE_ANSWER = 'UPDATE_ANSWER';
export const REMOVE_ANSWER = 'REMOVE_ANSWER';
export const CLEAR_ANSWER = 'CLEAR_ANSWER';
export const QUESTIONS_LIST_STAGES = [
    'QUESTION_LIST_FETCHING',
    'QUESTION_LIST_FETCH',
    'QUESTION_LIST_FAIL_FETCH'
];